/* soapH.h
   Generated by gSOAP 2.8.14 from bestpay.h

Copyright(C) 2000-2013, Robert van Engelen, Genivia Inc. All Rights Reserved.
The generated code is released under ONE of the following licenses:
GPL or Genivia's license for commercial use.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifndef WITH_NOIDREF

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif

#ifdef __cplusplus
extern "C" {
#endif
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);

#ifdef __cplusplus
}
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

SOAP_FMAC3 const char ** SOAP_FMAC4 soap_faultcode(struct soap *soap);

SOAP_FMAC3 void * SOAP_FMAC4 soap_instantiate(struct soap*, int, const char*, const char*, size_t*);
SOAP_FMAC3 int SOAP_FMAC4 soap_fdelete(struct soap_clist*);
SOAP_FMAC3 void* SOAP_FMAC4 soap_class_id_enter(struct soap*, const char*, void*, int, size_t, const char*, const char*);

SOAP_FMAC3 void* SOAP_FMAC4 soap_container_id_forward(struct soap*, const char*, void*, size_t, int, int, size_t, unsigned int);

SOAP_FMAC3 void SOAP_FMAC4 soap_container_insert(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);

#ifndef soap_write_byte
#define soap_write_byte(soap, data) ( soap_begin(soap), soap_serialize_byte(soap, data), soap_begin_send(soap) || soap_put_byte(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);

#ifndef soap_read_byte
#define soap_read_byte(soap, data) ( soap_begin_recv(soap) || !soap_get_byte(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);

#ifndef soap_write_int
#define soap_write_int(soap, data) ( soap_begin(soap), soap_serialize_int(soap, data), soap_begin_send(soap) || soap_put_int(soap, data, "int", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);

#ifndef soap_read_int
#define soap_read_int(soap, data) ( soap_begin_recv(soap) || !soap_get_int(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_std__string
#define SOAP_TYPE_std__string (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_std__string(struct soap*, std::string *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_std__string(struct soap*, const std::string *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_std__string(struct soap*, const char*, int, const std::string*, const char*);
SOAP_FMAC3 std::string * SOAP_FMAC4 soap_in_std__string(struct soap*, const char*, std::string*, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_std__string(struct soap*, const std::string *, const char*, const char*);

#ifndef soap_write_std__string
#define soap_write_std__string(soap, data) ( soap_begin(soap), soap_serialize_std__string(soap, data), soap_begin_send(soap) || soap_put_std__string(soap, data, "string", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 std::string * SOAP_FMAC4 soap_get_std__string(struct soap*, std::string *, const char*, const char*);

#ifndef soap_read_std__string
#define soap_read_std__string(soap, data) ( soap_begin_recv(soap) || !soap_get_std__string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 std::string * SOAP_FMAC2 soap_instantiate_std__string(struct soap*, int, const char*, const char*, size_t*);

inline std::string * soap_new_std__string(struct soap *soap, int n = -1) { return soap_instantiate_std__string(soap, n, NULL, NULL, NULL); }

inline std::string * soap_new_req_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline std::string * soap_new_set_std__string(struct soap *soap) { std::string *_p = soap_instantiate_std__string(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_std__string(soap, _p); } return _p; }

inline void soap_delete_std__string(struct soap *soap, std::string *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_std__string(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Fault
#define soap_write_SOAP_ENV__Fault(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Fault(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Fault(soap, data, "SOAP-ENV:Fault", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Fault
#define soap_read_SOAP_ENV__Fault(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Fault(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Fault * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Fault(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Fault * soap_new_SOAP_ENV__Fault(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Fault(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Fault * soap_new_req_SOAP_ENV__Fault(struct soap *soap) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); } return _p; }

inline struct SOAP_ENV__Fault * soap_new_set_SOAP_ENV__Fault(struct soap *soap, char *faultcode, char *faultstring, char *faultactor, struct SOAP_ENV__Detail *detail, struct SOAP_ENV__Code *SOAP_ENV__Code, struct SOAP_ENV__Reason *SOAP_ENV__Reason, char *SOAP_ENV__Node, char *SOAP_ENV__Role, struct SOAP_ENV__Detail *SOAP_ENV__Detail) { struct SOAP_ENV__Fault *_p = soap_instantiate_SOAP_ENV__Fault(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Fault(soap, _p); _p->faultcode = faultcode; _p->faultstring = faultstring; _p->faultactor = faultactor; _p->detail = detail; _p->SOAP_ENV__Code = SOAP_ENV__Code; _p->SOAP_ENV__Reason = SOAP_ENV__Reason; _p->SOAP_ENV__Node = SOAP_ENV__Node; _p->SOAP_ENV__Role = SOAP_ENV__Role; _p->SOAP_ENV__Detail = SOAP_ENV__Detail; } return _p; }

inline void soap_delete_SOAP_ENV__Fault(struct soap *soap, struct SOAP_ENV__Fault *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Fault(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Reason
#define soap_write_SOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Reason
#define soap_read_SOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Reason * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Reason(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Reason * soap_new_SOAP_ENV__Reason(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Reason(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Reason * soap_new_req_SOAP_ENV__Reason(struct soap *soap) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); } return _p; }

inline struct SOAP_ENV__Reason * soap_new_set_SOAP_ENV__Reason(struct soap *soap, char *SOAP_ENV__Text) { struct SOAP_ENV__Reason *_p = soap_instantiate_SOAP_ENV__Reason(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Reason(soap, _p); _p->SOAP_ENV__Text = SOAP_ENV__Text; } return _p; }

inline void soap_delete_SOAP_ENV__Reason(struct soap *soap, struct SOAP_ENV__Reason *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Reason(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Detail
#define soap_write_SOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Detail
#define soap_read_SOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Detail * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Detail(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Detail * soap_new_SOAP_ENV__Detail(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Detail(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Detail * soap_new_req_SOAP_ENV__Detail(struct soap *soap, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__type = __type; _p->fault = fault; } return _p; }

inline struct SOAP_ENV__Detail * soap_new_set_SOAP_ENV__Detail(struct soap *soap, char *__any, int __type, void *fault) { struct SOAP_ENV__Detail *_p = soap_instantiate_SOAP_ENV__Detail(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Detail(soap, _p); _p->__any = __any; _p->__type = __type; _p->fault = fault; } return _p; }

inline void soap_delete_SOAP_ENV__Detail(struct soap *soap, struct SOAP_ENV__Detail *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Detail(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Code
#define soap_write_SOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Code
#define soap_read_SOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Code * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Code(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Code * soap_new_SOAP_ENV__Code(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Code(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Code * soap_new_req_SOAP_ENV__Code(struct soap *soap) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); } return _p; }

inline struct SOAP_ENV__Code * soap_new_set_SOAP_ENV__Code(struct soap *soap, char *SOAP_ENV__Value, struct SOAP_ENV__Code *SOAP_ENV__Subcode) { struct SOAP_ENV__Code *_p = soap_instantiate_SOAP_ENV__Code(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Code(soap, _p); _p->SOAP_ENV__Value = SOAP_ENV__Value; _p->SOAP_ENV__Subcode = SOAP_ENV__Subcode; } return _p; }

inline void soap_delete_SOAP_ENV__Code(struct soap *soap, struct SOAP_ENV__Code *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Code(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_write_SOAP_ENV__Header
#define soap_write_SOAP_ENV__Header(soap, data) ( soap_begin(soap), soap_serialize_SOAP_ENV__Header(soap, data), soap_begin_send(soap) || soap_put_SOAP_ENV__Header(soap, data, "SOAP-ENV:Header", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);

#ifndef soap_read_SOAP_ENV__Header
#define soap_read_SOAP_ENV__Header(soap, data) ( soap_begin_recv(soap) || !soap_get_SOAP_ENV__Header(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct SOAP_ENV__Header * SOAP_FMAC2 soap_instantiate_SOAP_ENV__Header(struct soap*, int, const char*, const char*, size_t*);

inline struct SOAP_ENV__Header * soap_new_SOAP_ENV__Header(struct soap *soap, int n = -1) { return soap_instantiate_SOAP_ENV__Header(soap, n, NULL, NULL, NULL); }

inline struct SOAP_ENV__Header * soap_new_req_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline struct SOAP_ENV__Header * soap_new_set_SOAP_ENV__Header(struct soap *soap) { struct SOAP_ENV__Header *_p = soap_instantiate_SOAP_ENV__Header(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_SOAP_ENV__Header(soap, _p); } return _p; }

inline void soap_delete_SOAP_ENV__Header(struct soap *soap, struct SOAP_ENV__Header *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_SOAP_ENV__Header(struct soap*, int, int, void*, size_t, const void*, size_t);

#endif

#ifndef SOAP_TYPE_ns1__dispatchCommandEXT
#define SOAP_TYPE_ns1__dispatchCommandEXT (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommandEXT(struct soap*, struct ns1__dispatchCommandEXT *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommandEXT(struct soap*, const struct ns1__dispatchCommandEXT *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommandEXT(struct soap*, const char*, int, const struct ns1__dispatchCommandEXT *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommandEXT * SOAP_FMAC4 soap_in_ns1__dispatchCommandEXT(struct soap*, const char*, struct ns1__dispatchCommandEXT *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommandEXT(struct soap*, const struct ns1__dispatchCommandEXT *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommandEXT
#define soap_write_ns1__dispatchCommandEXT(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommandEXT(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommandEXT(soap, data, "ns1:dispatchCommandEXT", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommandEXT * SOAP_FMAC4 soap_get_ns1__dispatchCommandEXT(struct soap*, struct ns1__dispatchCommandEXT *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommandEXT
#define soap_read_ns1__dispatchCommandEXT(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommandEXT(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommandEXT * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommandEXT(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommandEXT * soap_new_ns1__dispatchCommandEXT(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommandEXT(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommandEXT * soap_new_req_ns1__dispatchCommandEXT(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommandEXT *_p = soap_instantiate_ns1__dispatchCommandEXT(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandEXT(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline struct ns1__dispatchCommandEXT * soap_new_set_ns1__dispatchCommandEXT(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommandEXT *_p = soap_instantiate_ns1__dispatchCommandEXT(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandEXT(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline void soap_delete_ns1__dispatchCommandEXT(struct soap *soap, struct ns1__dispatchCommandEXT *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommandEXT(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dispatchCommandEXTResponse
#define SOAP_TYPE_ns1__dispatchCommandEXTResponse (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommandEXTResponse(struct soap*, struct ns1__dispatchCommandEXTResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommandEXTResponse(struct soap*, const struct ns1__dispatchCommandEXTResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommandEXTResponse(struct soap*, const char*, int, const struct ns1__dispatchCommandEXTResponse *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommandEXTResponse * SOAP_FMAC4 soap_in_ns1__dispatchCommandEXTResponse(struct soap*, const char*, struct ns1__dispatchCommandEXTResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommandEXTResponse(struct soap*, const struct ns1__dispatchCommandEXTResponse *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommandEXTResponse
#define soap_write_ns1__dispatchCommandEXTResponse(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommandEXTResponse(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommandEXTResponse(soap, data, "ns1:dispatchCommandEXTResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommandEXTResponse * SOAP_FMAC4 soap_get_ns1__dispatchCommandEXTResponse(struct soap*, struct ns1__dispatchCommandEXTResponse *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommandEXTResponse
#define soap_read_ns1__dispatchCommandEXTResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommandEXTResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommandEXTResponse * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommandEXTResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommandEXTResponse * soap_new_ns1__dispatchCommandEXTResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommandEXTResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommandEXTResponse * soap_new_req_ns1__dispatchCommandEXTResponse(struct soap *soap, std::string& _dispatchCommandEXTReturn) { struct ns1__dispatchCommandEXTResponse *_p = soap_instantiate_ns1__dispatchCommandEXTResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandEXTResponse(soap, _p); _p->_dispatchCommandEXTReturn = _dispatchCommandEXTReturn; } return _p; }

inline struct ns1__dispatchCommandEXTResponse * soap_new_set_ns1__dispatchCommandEXTResponse(struct soap *soap, std::string& _dispatchCommandEXTReturn) { struct ns1__dispatchCommandEXTResponse *_p = soap_instantiate_ns1__dispatchCommandEXTResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandEXTResponse(soap, _p); _p->_dispatchCommandEXTReturn = _dispatchCommandEXTReturn; } return _p; }

inline void soap_delete_ns1__dispatchCommandEXTResponse(struct soap *soap, struct ns1__dispatchCommandEXTResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommandEXTResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dispatchCommandIPOS
#define SOAP_TYPE_ns1__dispatchCommandIPOS (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommandIPOS(struct soap*, struct ns1__dispatchCommandIPOS *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommandIPOS(struct soap*, const struct ns1__dispatchCommandIPOS *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommandIPOS(struct soap*, const char*, int, const struct ns1__dispatchCommandIPOS *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommandIPOS * SOAP_FMAC4 soap_in_ns1__dispatchCommandIPOS(struct soap*, const char*, struct ns1__dispatchCommandIPOS *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommandIPOS(struct soap*, const struct ns1__dispatchCommandIPOS *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommandIPOS
#define soap_write_ns1__dispatchCommandIPOS(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommandIPOS(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommandIPOS(soap, data, "ns1:dispatchCommandIPOS", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommandIPOS * SOAP_FMAC4 soap_get_ns1__dispatchCommandIPOS(struct soap*, struct ns1__dispatchCommandIPOS *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommandIPOS
#define soap_read_ns1__dispatchCommandIPOS(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommandIPOS(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommandIPOS * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommandIPOS(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommandIPOS * soap_new_ns1__dispatchCommandIPOS(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommandIPOS(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommandIPOS * soap_new_req_ns1__dispatchCommandIPOS(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommandIPOS *_p = soap_instantiate_ns1__dispatchCommandIPOS(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandIPOS(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline struct ns1__dispatchCommandIPOS * soap_new_set_ns1__dispatchCommandIPOS(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommandIPOS *_p = soap_instantiate_ns1__dispatchCommandIPOS(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandIPOS(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline void soap_delete_ns1__dispatchCommandIPOS(struct soap *soap, struct ns1__dispatchCommandIPOS *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommandIPOS(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dispatchCommandIPOSResponse
#define SOAP_TYPE_ns1__dispatchCommandIPOSResponse (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommandIPOSResponse(struct soap*, struct ns1__dispatchCommandIPOSResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommandIPOSResponse(struct soap*, const struct ns1__dispatchCommandIPOSResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommandIPOSResponse(struct soap*, const char*, int, const struct ns1__dispatchCommandIPOSResponse *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommandIPOSResponse * SOAP_FMAC4 soap_in_ns1__dispatchCommandIPOSResponse(struct soap*, const char*, struct ns1__dispatchCommandIPOSResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommandIPOSResponse(struct soap*, const struct ns1__dispatchCommandIPOSResponse *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommandIPOSResponse
#define soap_write_ns1__dispatchCommandIPOSResponse(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommandIPOSResponse(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommandIPOSResponse(soap, data, "ns1:dispatchCommandIPOSResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommandIPOSResponse * SOAP_FMAC4 soap_get_ns1__dispatchCommandIPOSResponse(struct soap*, struct ns1__dispatchCommandIPOSResponse *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommandIPOSResponse
#define soap_read_ns1__dispatchCommandIPOSResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommandIPOSResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommandIPOSResponse * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommandIPOSResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommandIPOSResponse * soap_new_ns1__dispatchCommandIPOSResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommandIPOSResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommandIPOSResponse * soap_new_req_ns1__dispatchCommandIPOSResponse(struct soap *soap, std::string& _dispatchCommandIPOSReturn) { struct ns1__dispatchCommandIPOSResponse *_p = soap_instantiate_ns1__dispatchCommandIPOSResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandIPOSResponse(soap, _p); _p->_dispatchCommandIPOSReturn = _dispatchCommandIPOSReturn; } return _p; }

inline struct ns1__dispatchCommandIPOSResponse * soap_new_set_ns1__dispatchCommandIPOSResponse(struct soap *soap, std::string& _dispatchCommandIPOSReturn) { struct ns1__dispatchCommandIPOSResponse *_p = soap_instantiate_ns1__dispatchCommandIPOSResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandIPOSResponse(soap, _p); _p->_dispatchCommandIPOSReturn = _dispatchCommandIPOSReturn; } return _p; }

inline void soap_delete_ns1__dispatchCommandIPOSResponse(struct soap *soap, struct ns1__dispatchCommandIPOSResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommandIPOSResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dispatchCommand
#define SOAP_TYPE_ns1__dispatchCommand (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommand(struct soap*, struct ns1__dispatchCommand *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommand(struct soap*, const struct ns1__dispatchCommand *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommand(struct soap*, const char*, int, const struct ns1__dispatchCommand *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommand * SOAP_FMAC4 soap_in_ns1__dispatchCommand(struct soap*, const char*, struct ns1__dispatchCommand *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommand(struct soap*, const struct ns1__dispatchCommand *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommand
#define soap_write_ns1__dispatchCommand(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommand(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommand(soap, data, "ns1:dispatchCommand", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommand * SOAP_FMAC4 soap_get_ns1__dispatchCommand(struct soap*, struct ns1__dispatchCommand *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommand
#define soap_read_ns1__dispatchCommand(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommand(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommand * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommand(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommand * soap_new_ns1__dispatchCommand(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommand(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommand * soap_new_req_ns1__dispatchCommand(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommand *_p = soap_instantiate_ns1__dispatchCommand(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommand(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline struct ns1__dispatchCommand * soap_new_set_ns1__dispatchCommand(struct soap *soap, std::string& _in0, std::string& _in1) { struct ns1__dispatchCommand *_p = soap_instantiate_ns1__dispatchCommand(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommand(soap, _p); _p->_in0 = _in0; _p->_in1 = _in1; } return _p; }

inline void soap_delete_ns1__dispatchCommand(struct soap *soap, struct ns1__dispatchCommand *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommand(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef SOAP_TYPE_ns1__dispatchCommandResponse
#define SOAP_TYPE_ns1__dispatchCommandResponse (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__dispatchCommandResponse(struct soap*, struct ns1__dispatchCommandResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__dispatchCommandResponse(struct soap*, const struct ns1__dispatchCommandResponse *);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__dispatchCommandResponse(struct soap*, const char*, int, const struct ns1__dispatchCommandResponse *, const char*);
SOAP_FMAC3 struct ns1__dispatchCommandResponse * SOAP_FMAC4 soap_in_ns1__dispatchCommandResponse(struct soap*, const char*, struct ns1__dispatchCommandResponse *, const char*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__dispatchCommandResponse(struct soap*, const struct ns1__dispatchCommandResponse *, const char*, const char*);

#ifndef soap_write_ns1__dispatchCommandResponse
#define soap_write_ns1__dispatchCommandResponse(soap, data) ( soap_begin(soap), soap_serialize_ns1__dispatchCommandResponse(soap, data), soap_begin_send(soap) || soap_put_ns1__dispatchCommandResponse(soap, data, "ns1:dispatchCommandResponse", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct ns1__dispatchCommandResponse * SOAP_FMAC4 soap_get_ns1__dispatchCommandResponse(struct soap*, struct ns1__dispatchCommandResponse *, const char*, const char*);

#ifndef soap_read_ns1__dispatchCommandResponse
#define soap_read_ns1__dispatchCommandResponse(soap, data) ( soap_begin_recv(soap) || !soap_get_ns1__dispatchCommandResponse(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif

SOAP_FMAC1 struct ns1__dispatchCommandResponse * SOAP_FMAC2 soap_instantiate_ns1__dispatchCommandResponse(struct soap*, int, const char*, const char*, size_t*);

inline struct ns1__dispatchCommandResponse * soap_new_ns1__dispatchCommandResponse(struct soap *soap, int n = -1) { return soap_instantiate_ns1__dispatchCommandResponse(soap, n, NULL, NULL, NULL); }

inline struct ns1__dispatchCommandResponse * soap_new_req_ns1__dispatchCommandResponse(struct soap *soap, std::string& _dispatchCommandReturn) { struct ns1__dispatchCommandResponse *_p = soap_instantiate_ns1__dispatchCommandResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandResponse(soap, _p); _p->_dispatchCommandReturn = _dispatchCommandReturn; } return _p; }

inline struct ns1__dispatchCommandResponse * soap_new_set_ns1__dispatchCommandResponse(struct soap *soap, std::string& _dispatchCommandReturn) { struct ns1__dispatchCommandResponse *_p = soap_instantiate_ns1__dispatchCommandResponse(soap, -1, NULL, NULL, NULL); if (_p) { soap_default_ns1__dispatchCommandResponse(soap, _p); _p->_dispatchCommandReturn = _dispatchCommandReturn; } return _p; }

inline void soap_delete_ns1__dispatchCommandResponse(struct soap *soap, struct ns1__dispatchCommandResponse *p) { soap_delete(soap, p); }

SOAP_FMAC3 void SOAP_FMAC4 soap_copy_ns1__dispatchCommandResponse(struct soap*, int, int, void*, size_t, const void*, size_t);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Reason
#define soap_write_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Reason(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Reason(soap, data, "SOAP-ENV:Reason", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Reason
#define soap_read_PointerToSOAP_ENV__Reason(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Reason(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Detail
#define soap_write_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Detail(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Detail(soap, data, "SOAP-ENV:Detail", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Detail
#define soap_read_PointerToSOAP_ENV__Detail(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Detail(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);

#ifndef soap_write_PointerToSOAP_ENV__Code
#define soap_write_PointerToSOAP_ENV__Code(soap, data) ( soap_begin(soap), soap_serialize_PointerToSOAP_ENV__Code(soap, data), soap_begin_send(soap) || soap_put_PointerToSOAP_ENV__Code(soap, data, "SOAP-ENV:Code", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);

#ifndef soap_read_PointerToSOAP_ENV__Code
#define soap_read_PointerToSOAP_ENV__Code(soap, data) ( soap_begin_recv(soap) || !soap_get_PointerToSOAP_ENV__Code(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)

SOAP_FMAC3 void SOAP_FMAC4 soap_serialize__QName(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write__QName
#define soap_write__QName(soap, data) ( soap_begin(soap), soap_serialize__QName(soap, data), soap_begin_send(soap) || soap_put__QName(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);

#ifndef soap_read__QName
#define soap_read__QName(soap, data) ( soap_begin_recv(soap) || !soap_get__QName(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);

#ifndef soap_write_string
#define soap_write_string(soap, data) ( soap_begin(soap), soap_serialize_string(soap, data), soap_begin_send(soap) || soap_put_string(soap, data, "byte", NULL) || soap_end_send(soap), soap->error )
#endif

SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);

#ifndef soap_read_string
#define soap_read_string(soap, data) ( soap_begin_recv(soap) || !soap_get_string(soap, data, NULL, NULL) || soap_end_recv(soap), soap->error )
#endif


#endif

/* End of soapH.h */
